# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="cyberbrain",
    version="0.0.0.1",
    description="A Cyberbrain that helps you remember everything.",
    python_requires=">=3.7.0",
    author="laike9m",
    author_email="laike9m@gmail.com",
    packages=["cyberbrain"],
    package_dir={"": "."},
    package_data={},
    install_requires=["crayons==0.*,>=0.3.0", "deepdiff", "pygments==2.*,>=2.6.1"],
    dependency_links=["git+https://github.com/seperman/deepdiff@dev#egg=deepdiff"],
    extras_require={
        "dev": [
            "dephell==0.*,>=0.8.3",
            "pyhamcrest==2.*,>=2.0.2",
            "pytest",
            "pytest-xdist==1.*,>=1.31.0",
            "tox==3.*,>=3.14.0",
            "tox-pyenv==1.*,>=1.1.0",
        ]
    },
)
