
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='cyberbrain',
    version='0.0.1',
    description='Python debugging. Redefined.',
    python_requires='==3.*,>=3.7.0',
    author='laike9m',
    author_email='laike9m@gmail.com',
    packages=['Cyberbrain'],
    package_dir={"": "."},
    package_data={},
    install_requires=['attrs==19.*,>=19.3.0', 'crayons==0.*,>=0.3.0', 'deepdiff==5.*,>=5.0.0', 'get-port==0.*,>=0.0.5', 'grpcio==1.*,>=1.30.0', 'jsonpickle==1.*,>=1.4.1', 'protobuf==3.*,>=3.12.2', 'pygments==2.*,>=2.6.1', 'shortuuid==1.*,>=1.0.1', 'typing-extensions==3.*,>=3.7.4'],
    extras_require={"dev": ["bytecode==0.*,>=0.11.0", "dephell==0.*,>=0.8.3", "emoji==0.*,>=0.6.0", "fire==0.*,>=0.3.1", "grpcio-tools==1.*,>=1.30.0", "pyhamcrest==2.*,>=2.0.2", "pytest==6.*,>=6.0.1", "pytest-xdist==1.*,>=1.31.0", "tox==3.*,>=3.14.0", "tox-pyenv==1.*,>=1.1.0"]},
)
