# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="cyberbrain",
    version="0.0.0.1",
    description="A Cyberbrain that helps you remember everything.",
    python_requires="==3.*,>=3.7.0",
    author="laike9m",
    author_email="laike9m@gmail.com",
    packages=["cyberbrain", "cyberbrain.rpc"],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        "crayons==0.*,>=0.3.0",
        "deepdiff==5.*,>=5.0.0",
        "grpcio==1.*,>=1.30.0",
        "protobuf==3.*,>=3.12.2",
        "pygments==2.*,>=2.6.1",
    ],
    extras_require={
        "dev": [
            "bytecode==0.*,>=0.11.0",
            "dephell==0.*,>=0.8.3",
            "grpcio-tools==1.*,>=1.30.0",
            "pyhamcrest==2.*,>=2.0.2",
            "pytest",
            "pytest-xdist==1.*,>=1.31.0",
            "tox==3.*,>=3.14.0",
            "tox-pyenv==1.*,>=1.1.0",
        ]
    },
)
