#!/usr/bin/env bash

#TS_OUT=./src/rpc
#
#npx grpc_tools_node_protoc \
#    --js_out=import_style=commonjs,binary:$TS_OUT \
#    --grpc_out=grpc_js:$TS_OUT \
#    -I ../protos \
#    ../protos/*.proto


IN_DIR="../protos"
OUT_DIR="./out/rpc"
TS_OUT_DIR="./src/rpc"
PROTOC="$(npm bin)/grpc_tools_node_protoc"
PROTOC_GEN_TS="$(npm bin)/protoc-gen-ts"

$PROTOC \
    -I=$IN_DIR \
    --plugin=protoc-gen-ts="$PROTOC_GEN_TS" \
    --js_out=import_style=commonjs:$OUT_DIR \
    --grpc_out=grpc_js:$OUT_DIR \
    --ts_out=service=grpc-node:$TS_OUT_DIR \
    $IN_DIR/*.proto

# Fix import paths within TypeScript files generated by `grpc_tools_node_protoc`
sed -i "" -e \
    "s/from \"grpc\"/from \"@grpc\/grpc-js\"/g" \
    "$TS_OUT_DIR/"*
