#!/usr/bin/env bash

IN_DIR="../protos"
OUT_DIR="./out/generated"
TS_OUT_DIR="./src/generated"
PROTOC="$(npm bin)/grpc_tools_node_protoc"
PROTOC_GEN_TS="$(npm bin)/protoc-gen-ts"

mkdir -p $TS_OUT_DIR
mkdir -p $OUT_DIR

$PROTOC \
    -I=$IN_DIR \
    --plugin=protoc-gen-ts="$PROTOC_GEN_TS" \
    --js_out=import_style=commonjs:$OUT_DIR \
    --grpc_out=grpc_js:$OUT_DIR \
    --ts_out=service=grpc-node:$TS_OUT_DIR \
    $IN_DIR/*.proto

# Fix import paths within TypeScript files generated by `grpc_tools_node_protoc`
sed -i "" -e \
    "s/from \"grpc\"/from \"@grpc\/grpc-js\"/g" \
    "$TS_OUT_DIR/"*
