name: Tests

# Ideally we should trigger different checks based on modified sources.
# For example, ignore Python tests if only js files are modified.
# There's a hacky way: https://stackoverflow.com/a/59608109/2142577
# TODO: Investigate whether GitHub Actions support it.
on:
  pull_request:
    paths:
      - "cyberbrain/*"
      - "cyberbrain-vsc/*"
      - "test/*"
      - ".github/workflows/ci.yml"
      - "pdm.lock"
      - "tox.ini"
  push:
    paths:
      - "cyberbrain/*"
      - "cyberbrain-vsc/*"
      - "test/*"
      - ".github/workflows/ci.yml"
      - "pdm.lock"
      - "tox.ini"
  workflow_dispatch:

jobs:
  PythonLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
             python -m pip install black==22.3.0
             black --check cyberbrain test

  JsLintAndTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cyberbrain-vsc
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run lint
    - run: npm run unittest

  PythonTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10" ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - run: pdm info -v
      - name: Install dependencies
        run: pdm install -v
      - name: Run tests
        run: pdm run tox -v

  VsCodeTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10" ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - run: pdm info -v
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Python dependencies
        run: pdm install -v
      - name: Install Node.js dependencies
        run: npm install
        working-directory: cyberbrain-vsc
      - name: VSCode Integration tests on Linux
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
        working-directory: cyberbrain-vsc
      - name: VSCode Integration tests on Mac & Win
        run: npm test
        if: runner.os != 'Linux'
        working-directory: cyberbrain-vsc
